refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%dT%H:%M:%S%z)} - [{l}] [{M}] - {h({m})}{n}"
  auth-service:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%dT%H:%M:%S%z)} - [{l}] [{M}] - {h({m})}{n}"
root:
  level: debug
  appenders:
    - stdout
loggers:
  auth_service:
    level: trace
    appenders:
      - auth-service
    additive: false
