
[global]
template_dir = "auth-service-web/templates/"
static_dir = "auth-service-web/static/"

[development]
jwt_key = "dev_key"
jwt_exp = 86400

[development.databases]
db = { url = "postgres://postgres:postgres@localhost:5432/auth_service" }
